//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.18 at 12:25:30 PM IST 
//


package com.nosqldo.template;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="field" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="coulumFamily" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="query" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="update" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="rowKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operationType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataStore" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tableName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "field"
})
@XmlRootElement(name = "dataTemplate")
public class DataTemplate {

   

	@XmlElement(required = true)
    protected List<DataTemplate.Field> field;
    @XmlAttribute(name = "rowKey")
    protected String rowKey;
    @XmlAttribute(name = "operationType")
    protected String operationType;
    @XmlAttribute(name = "dataStore")
    protected String dataStore;
    @XmlAttribute(name = "tableName")
    protected String tableName;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataTemplate.Field }
     * 
     * 
     */
    public List<DataTemplate.Field> getField() {
        if (field == null) {
            field = new ArrayList<DataTemplate.Field>();
        }
        return this.field;
    }

    /**
     * Gets the value of the rowKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowKey() {
        return rowKey;
    }

    /**
     * Sets the value of the rowKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowKey(String value) {
        this.rowKey = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the dataStore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataStore() {
        return dataStore;
    }

    /**
     * Sets the value of the dataStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataStore(String value) {
        this.dataStore = value;
    }

    /**
     * Gets the value of the tableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * Sets the value of the tableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableName(String value) {
        this.tableName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="coulumFamily" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="query" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="update" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Field {

      

		@XmlAttribute(name = "property")
        protected String property;
        @XmlAttribute(name = "value")
        protected String value;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "coulumFamily")
        protected String coulumFamily;
        @XmlAttribute(name = "query")
        protected String query;
        @XmlAttribute(name = "update")
        protected String update;

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the coulumFamily property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCoulumFamily() {
            return coulumFamily;
        }

        /**
         * Sets the value of the coulumFamily property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCoulumFamily(String value) {
            this.coulumFamily = value;
        }

        /**
         * Gets the value of the query property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQuery() {
            return query;
        }

        /**
         * Sets the value of the query property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQuery(String value) {
            this.query = value;
        }

        /**
         * Gets the value of the update property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUpdate() {
            return update;
        }

        /**
         * Sets the value of the update property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUpdate(String value) {
            this.update = value;
        }
        
        @Override
      		public String toString() {
      			return "Field [property=" + property + ", value=" + value
      					+ ", name=" + name + ", coulumFamily=" + coulumFamily
      					+ ", query=" + query + ", update=" + update + "]";
      		}

    }

    @Override
   	public String toString() {
   		return "DataTemplate [field=" + field + ", rowKey=" + rowKey
   				+ ", operationType=" + operationType + ", dataStore="
   				+ dataStore + ", tableName=" + tableName + "]";
   	}

}
